server:
  port: 8080

cors:
  allowed-origins: http://localhost:5173

spring:
  application:
    name: pickup-system

  datasource:
    url: jdbc:mysql://localhost:3306/pickup_system?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: dev-secret-key-dev-secret-key-dev-secret-key-123456
  expiration-ms: 86400000
